### ISSUE TITLE
UserRepository saveUsers query problem

### ISSUE THREAD

**Issue by fdirlikli** [kbastani/twitter-graph-analytics#2]
Isn't there a problem with the below query (in UserRepository) as users Set stores User objects and User class doesn't have userA and userB properties? Am I missing something here?

``` java
    @Query("FOREACH(x in {users} | MERGE (a:User { profileId: x.userA.profileId })\n" +
              "MERGE (b:User { profileId: x.userB.profileId })\n" +
              "MERGE (a)-[:FOLLOWS]->(b))")
    Set<User> saveUsers(@Param("users") Set<User> users);
```

**Comment by kbastani** [comment]
You are correct. I will remove this method.

**Comment by kbastani** [comment]
Fixed in https://github.com/kbastani/spring-boot-graph-processing-example/commit/7483199b956bce290509b09b045d890669385b3d
