### ISSUE TITLE
Build's functions and flow

### ISSUE THREAD

**Issue by rokka-n** [kbastani/twitter-graph-analytics#7]
Hi,

Thank you for the talk yesterday at dockerhq, it was very interesting.

I wanted to ask how build process configured. Looking at travis config, I see it runs integration-test.sh script. 

The script runs container kbastani/docker-run-ec2 and executes something else, ./aws-create-instance.sh

And that's where things become interesting. 
Are those containers build by another job from source? Or its what spring cloud supposed to do? 
Also, it's not clear what aws-create-instance.sh is, there is no source in repository for that script.

**Comment by kbastani** [comment]
This is a pending issue (https://github.com/kbastani/spring-boot-graph-processing-example/issues/5) I am working on to demonstrate how to use a cloud provider for ephemeral integration testing. The kbastani/docker-run-ec2 container provides a Docker container with the AWS CLI and scripts for creating and tearing down an EC2 instance with Docker compose installed.

**Comment by rokka-n** [comment]
That was a dumb question, sorry.
I overlooked that aws-create-instance.sh is actually part of the container.

Did you find any advantage to run ci tests from container, compare for example to test-kitchen?
